Repository googleapis/python-dataproc, pull requests merged in 2020-05, with the labels that each got.

#19 chore: update templates (via synth)
  .coveragerc
  .flake8
  .github/ISSUE_TEMPLATE/bug_report.md
  CONTRIBUTING.rst
  MANIFEST.in
  noxfile.py
  setup.cfg
  synth.metadata
Labels: cla: yes

#18 chore: Migrate python-dataproc synth.py from artman to bazel
  synth.py
Labels: cla: yes

#24 docs: updates docstrings
  .kokoro/release.sh
  google/cloud/dataproc_v1/proto/autoscaling_policies_pb2.py
  google/cloud/dataproc_v1/proto/clusters_pb2.py
  synth.metadata
Labels: cla: yes

#28 chore: change docstring formatting
  google/cloud/dataproc_v1/proto/autoscaling_policies_pb2.py
  google/cloud/dataproc_v1/proto/clusters_pb2.py
  google/cloud/dataproc_v1/proto/jobs_pb2.py
  google/cloud/dataproc_v1/proto/operations_pb2.py
  google/cloud/dataproc_v1/proto/workflow_templates_pb2.py
  google/cloud/dataproc_v1beta2/proto/autoscaling_policies_pb2.py
  google/cloud/dataproc_v1beta2/proto/clusters_pb2.py
  google/cloud/dataproc_v1beta2/proto/jobs_pb2.py
  google/cloud/dataproc_v1beta2/proto/operations_pb2.py
  google/cloud/dataproc_v1beta2/proto/workflow_templates_pb2.py
  synth.metadata
Labels: cla: yes, context: partial

#27 chore: change docstring formatting (via synth)
  google/cloud/dataproc_v1/proto/autoscaling_policies_pb2.py
  google/cloud/dataproc_v1/proto/clusters_pb2.py
Labels: cla: yes, context: none

#32 chore: add create_key to all pb2s
  google/cloud/dataproc_v1/proto/autoscaling_policies_pb2.py
  google/cloud/dataproc_v1/proto/clusters_pb2.py
  google/cloud/dataproc_v1/proto/jobs_pb2.py
  google/cloud/dataproc_v1/proto/operations_pb2.py
  google/cloud/dataproc_v1/proto/shared_pb2.py
  google/cloud/dataproc_v1/proto/workflow_templates_pb2.py
  google/cloud/dataproc_v1beta2/proto/autoscaling_policies_pb2.py
  google/cloud/dataproc_v1beta2/proto/clusters_pb2.py
  google/cloud/dataproc_v1beta2/proto/jobs_pb2.py
  google/cloud/dataproc_v1beta2/proto/operations_pb2.py
  google/cloud/dataproc_v1beta2/proto/shared_pb2.py
  google/cloud/dataproc_v1beta2/proto/workflow_templates_pb2.py
  synth.metadata
Labels: cla: yes, context: partial
