Repository googleapis/python-dataproc, pull requests merged in 2020-08, with the labels that each got.

#66 chore: move samples from python-docs-sample
  .github/CODEOWNERS
  .gitignore
  .kokoro/build.sh
  .kokoro/docker/docs/Dockerfile
  .kokoro/docker/docs/fetch_gpg_keys.sh
  .kokoro/docs/common.cfg
  .kokoro/docs/docs-presubmit.cfg
  .kokoro/publish-docs.sh
  .kokoro/trampoline_v2.sh
  .trampolinerc
  docs/conf.py
  noxfile.py
  samples/AUTHORING_GUIDE.md
  samples/CONTRIBUTING.md
  samples/snippets/README.md
  samples/snippets/create_cluster.py
  samples/snippets/create_cluster_test.py
  samples/snippets/dataproc_e2e_donttest.py
  samples/snippets/instantiate_inline_workflow_template.py
  samples/snippets/instantiate_inline_workflow_template_test.py
  samples/snippets/list_clusters.py
  samples/snippets/noxfile.py
  samples/snippets/pyspark_sort.py
  samples/snippets/pyspark_sort_gcs.py
  samples/snippets/python-api-walkthrough.md
  samples/snippets/quickstart/quickstart.py
  samples/snippets/quickstart/quickstart_test.py
  samples/snippets/requirements-test.txt
  samples/snippets/requirements.txt
  samples/snippets/single_job_workflow.py
  samples/snippets/submit_job_to_cluster.py
  synth.metadata
  synth.py
Labels: cla: yes

#65 docs: change relative URLs to absolute URLs to fix broken links
  google/cloud/dataproc_v1/proto/autoscaling_policies.proto
  google/cloud/dataproc_v1/proto/autoscaling_policies_pb2.py
  google/cloud/dataproc_v1/proto/clusters_pb2.py
  synth.metadata
Labels: automerge, cla: yes, context: full

#72 chore: change docstring formatting
  google/cloud/dataproc_v1/proto/clusters_pb2.py
  synth.metadata
Labels: cla: yes, context: none

#77 docs: remove example usage from README
  README.rst
Labels: automerge, cla: yes
