Repository googleapis/python-dataproc, pull requests merged in 2020-06, with the labels that each got.

#34 chore: change formatting
  google/cloud/dataproc_v1/__init__.py
  google/cloud/dataproc_v1beta2/__init__.py
  synth.metadata
Labels: cla: yes, context: full

#35 chore: update docs formatting
  google/cloud/dataproc_v1/proto/clusters_pb2.py
  synth.metadata
Labels: cla: yes, context: none

#36 fix: increase timeout for `ClusterController` in v1
  google/cloud/dataproc_v1/gapic/cluster_controller_client_config.py
  google/cloud/dataproc_v1/proto/jobs.proto
  google/cloud/dataproc_v1/proto/jobs_pb2.py
  google/cloud/dataproc_v1beta2/proto/jobs.proto
  google/cloud/dataproc_v1beta2/proto/jobs_pb2.py
  synth.metadata
Labels: cla: yes, context: partial

#43 refactor: extend rpc timeout to 30 seconds
  google/cloud/dataproc_v1/gapic/workflow_template_service_client_config.py
  synth.metadata
Labels: cla: yes, context: partial

#44 feat: release as production/stable
  .repo-metadata.json
  README.rst
  setup.py
Labels: cla: yes

#46 chore: update docstring line spacing
  google/cloud/dataproc_v1/proto/autoscaling_policies_pb2.py
  google/cloud/dataproc_v1/proto/clusters_pb2.py
  google/cloud/dataproc_v1/proto/jobs_pb2.py
  google/cloud/dataproc_v1/proto/operations_pb2.py
  google/cloud/dataproc_v1/proto/workflow_templates_pb2.py
  google/cloud/dataproc_v1beta2/proto/autoscaling_policies_pb2.py
  google/cloud/dataproc_v1beta2/proto/clusters_pb2.py
  google/cloud/dataproc_v1beta2/proto/jobs_pb2.py
  google/cloud/dataproc_v1beta2/proto/operations_pb2.py
  google/cloud/dataproc_v1beta2/proto/workflow_templates_pb2.py
  synth.metadata
Labels: cla: yes, context: partial

#49 chore: change docstring formatting
  google/cloud/dataproc_v1/proto/clusters_pb2.py
  synth.metadata
Labels: cla: yes, context: none

#47 chore: update protobuf version
  google/cloud/dataproc_v1/proto/autoscaling_policies_pb2.py
  google/cloud/dataproc_v1/proto/autoscaling_policies_pb2_grpc.py
  google/cloud/dataproc_v1/proto/clusters_pb2.py
  google/cloud/dataproc_v1/proto/clusters_pb2_grpc.py
  google/cloud/dataproc_v1/proto/jobs_pb2.py
  google/cloud/dataproc_v1/proto/jobs_pb2_grpc.py
  google/cloud/dataproc_v1/proto/operations_pb2.py
  google/cloud/dataproc_v1/proto/operations_pb2_grpc.py
  google/cloud/dataproc_v1/proto/shared_pb2.py
  google/cloud/dataproc_v1/proto/shared_pb2_grpc.py
  google/cloud/dataproc_v1/proto/workflow_templates_pb2.py
  google/cloud/dataproc_v1/proto/workflow_templates_pb2_grpc.py
  google/cloud/dataproc_v1beta2/proto/autoscaling_policies_pb2.py
  google/cloud/dataproc_v1beta2/proto/autoscaling_policies_pb2_grpc.py
  google/cloud/dataproc_v1beta2/proto/clusters_pb2.py
  google/cloud/dataproc_v1beta2/proto/clusters_pb2_grpc.py
  google/cloud/dataproc_v1beta2/proto/jobs_pb2.py
  google/cloud/dataproc_v1beta2/proto/jobs_pb2_grpc.py
  google/cloud/dataproc_v1beta2/proto/operations_pb2.py
  google/cloud/dataproc_v1beta2/proto/operations_pb2_grpc.py
  google/cloud/dataproc_v1beta2/proto/shared_pb2.py
  google/cloud/dataproc_v1beta2/proto/shared_pb2_grpc.py
  google/cloud/dataproc_v1beta2/proto/workflow_templates_pb2.py
  google/cloud/dataproc_v1beta2/proto/workflow_templates_pb2_grpc.py
  synth.metadata
Labels: cla: yes, context: partial
